// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9dc__nBrbwpPmzcDfjU5DSQbTiKwQ4fM',
    appId: '1:772572261081:web:7023f9d505a155943e6cc8',
    messagingSenderId: '772572261081',
    projectId: 'test-firbase-9df3f',
    authDomain: 'test-firbase-9df3f.firebaseapp.com',
    storageBucket: 'test-firbase-9df3f.appspot.com',
    measurementId: 'G-BH1T74GY0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQAuA5bHboYzswB7GGwWbEfyeZKOiTS0M',
    appId: '1:772572261081:android:1f19ef939c9d4fd73e6cc8',
    messagingSenderId: '772572261081',
    projectId: 'test-firbase-9df3f',
    storageBucket: 'test-firbase-9df3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnqphxYtnCvDHTRV9yptsMSn_o751fJdE',
    appId: '1:772572261081:ios:297be954b303994f3e6cc8',
    messagingSenderId: '772572261081',
    projectId: 'test-firbase-9df3f',
    storageBucket: 'test-firbase-9df3f.appspot.com',
    iosBundleId: 'com.example.testFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnqphxYtnCvDHTRV9yptsMSn_o751fJdE',
    appId: '1:772572261081:ios:297be954b303994f3e6cc8',
    messagingSenderId: '772572261081',
    projectId: 'test-firbase-9df3f',
    storageBucket: 'test-firbase-9df3f.appspot.com',
    iosBundleId: 'com.example.testFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9dc__nBrbwpPmzcDfjU5DSQbTiKwQ4fM',
    appId: '1:772572261081:web:4b99abfd5be0d4783e6cc8',
    messagingSenderId: '772572261081',
    projectId: 'test-firbase-9df3f',
    authDomain: 'test-firbase-9df3f.firebaseapp.com',
    storageBucket: 'test-firbase-9df3f.appspot.com',
    measurementId: 'G-MJCPBFM9KJ',
  );
}
